# Generated by Django 3.0.2 on 2020-01-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bestMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('production_company', models.CharField(max_length=200)),
                ('vote_average', models.FloatField()),
                ('overview', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField()),
                ('original_language', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('cover_image', models.CharField(max_length=200)),
                ('backdrop_image', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('adult', models.BooleanField()),
            ],
        ),
    ]
